version: "3.8"

services:
  cz_portal_fe:
    image: ghcr.io/zeropage/cz_portal_fe:latest
    container_name: cz_portal_fe
    restart: always
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.zeropage.org
      - TZ=Asia/Seoul
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vue-project.rule=Host(`clug.zeropage.org`)"
      - "traefik.http.routers.vue-project.entrypoints=websecure"
      - "traefik.http.routers.vue-project.tls.certresolver=myresolver"
      - "traefik.http.services.vue-project.loadbalancer.server.port=4173"

networks:
  app-network:
    driver: bridge
